In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
match=pd.read_csv(r'C:\Users\A_R_COMPUTERS\Downloads\matches.csv')
delivery=pd.read_csv(r'C:\Users\A_R_COMPUTERS\Downloads\deliveries.csv\deliveries.csv')

In [2]:
delivery.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [3]:
match.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [4]:
total_score_df = delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()
total_score_df = total_score_df[total_score_df['inning'] == 1]

In [5]:
match_df = match.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on='match_id')
match_df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,184
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,183
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,163
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,143
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,136
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,171
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,155
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,152

In [6]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals'
]
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [7]:
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]
match_df.shape

(641, 20)

In [8]:
match_df.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3', 'match_id', 'total_runs'],
      dtype='object')

# how tosss affect the wining side!!!

In [9]:
match_df.head(30)

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,7,178
7,8,IPL-2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,8,148
9,10,IPL-2017,Mumbai,12-04-2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,10,158
10,11,IPL-2017,Kolkata,13-04-2017,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN,11,170
11,12,IPL-2017,Bangalore,14-04-2017,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,KA Pollard,M Chinnaswamy Stadium,KN Ananthapadmanabhan,AK Chaudhary,NaN,12,142
13,14,IPL-2017,Kolkata,15-04-2017,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,17,0,RV Uthappa,Eden Gardens,AY Dandekar,NJ Llong,NaN,14,172
14,15,IPL-2017,Delhi,15-04-2017,Delhi Capitals,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Delhi Daredevils,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN,15,188
17,18,IPL-2017,Delhi,17-04-2017,Delhi Capitals,Kolkata Knight Riders,Delhi Daredevils,bat,normal,0,Kolkata Knight Riders,0,4,NM Coulter-Nile,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN,18,168
18,19,IPL-2017,Hyderabad,17-04-2017,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN,19,159
20,21,IPL-2017,Hyderabad,19-04-2017,Sunrisers Hyderabad,Delhi Capitals,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,15,0,KS Williamson,"Rajiv Gandhi International Stadium, Uppal",CB Gaffaney,NJ Llong,NaN,21,191
21,22,IPL-2017,Indore,20-04-2017,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,JC Buttler,Holkar Cricket Stadium,M Erasmus,C Shamshuddin,NaN,22,198
23,24,IPL-2017,Mumbai,22-04-2017,Mumbai Indians,Delhi Capitals,Delhi Daredevils,field,normal,0,Mumbai Indians,14,0,MJ McClenaghan,Wankhede Stadium,A Nand Kishore,S Ravi,NaN,24,142
26,27,IPL-2017,Kolkata,23-04-2017,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,82,0,NM Coulter-Nile,Eden Gardens,CB Gaffaney,CK Nandan,NaN,27,131
30,31,IPL-2017,Kolkata,28-04-2017,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,G Gambhir,Eden Gardens,NJ Llong,S Ravi,NaN,31,160
31,32,IPL-2017,Chandigarh,28-04-2017,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,26,0,Rashid Khan,"Punjab Cricket Association IS Bindra Stadium, ...",Nitin Menon,CK Nandan,NaN,32,207
34,35,IPL-2017,Chandigarh,30-04-2017,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,10,Sandeep Sharma,"Punjab Cricket Association IS Bindra Stadium, ...",YC Barde,CK Nandan,NaN,35,67
35,36,IPL-2017,Hyderabad,30-04-2017,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,48,0,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,S Ravi,NaN,36,209
36,37,IPL-2017,Mumbai,01-05-2017,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,bat,normal,0,Mumbai Indians,0,5,RG Sharma,Wankhede Stadium,AK Chaudhary,CB Gaffaney,NaN,37,162
38,39,IPL-2017,Delhi,02-05-2017,Sunrisers Hyderabad,Delhi Capitals,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,6,Mohammed Shami,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN,39,185
41,42,IPL-2017,Bangalore,05-05-2017,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kings XI Punjab,19,0,Sandeep Sharma,M Chinnaswamy Stadium,CB Gaffaney,C Shamshuddin,NaN,42,138
43,44,IPL-2017,Delhi,06-05-2017,Mumbai Indians,Delhi Capitals,Delhi Daredevils,field,normal,0,Mumbai Indians,146,0,LMP Simmons,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN,44,212
44,45,IPL-2017,Bangalore,07-05-2017,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,6,SP Narine,M Chinnaswamy Stadium,AY Dandekar,C Shamshuddin,NaN,45,158
46,47,IPL-2017,Hyderabad,08-05-2017,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,normal,0,Sunrisers Hyderabad,0,7,S Dhawan,"Rajiv Gandhi International Stadium, Uppal",KN Ananthapadmanabhan,M Erasmus,NaN,47,138
47,48,IPL-2017,Chandigarh,09-05-2017,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kings XI Punjab,14,0,MM Sharma,"Punjab Cricket Association IS Bindra Stadium, ...",A Nand Kishore,S Ravi,NaN,48,167
49,50,IPL-2017,Mumbai,11-05-2017,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Kings XI Punjab,7,0,WP Saha,Wankhede Stadium,A Deshmukh,A Nand Kishore,NaN,50,230
52,53,IPL-2017,Kolkata,13-05-2017,Mumbai Indians,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Mumbai Indians,9,0,AT Rayudu,Eden Gardens,A Nand Kishore,S Ravi,NaN,53,173
54,55,IPL-2017,Delhi,14-05-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,10,0,HV Patel,Feroz Shah Kotla,CK Nandan,C Shamshuddin,NaN,55,161
56,57,IPL-2017,Bangalore,17-05-2017,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,1,Kolkata Knight Riders,0,7,NM Coulter-Nile,M Chinnaswamy Stadium,AK Chaudhary,Nitin Menon,NaN,57,128

In [10]:
match_df.toss_winner.value_counts()

Mumbai Indians                 89
Chennai Super Kings            86
Kolkata Knight Riders          82
Rajasthan Royals               76
Royal Challengers Bangalore    75
Kings XI Punjab                74
Delhi Daredevils               71
Sunrisers Hyderabad            39
Deccan Chargers                39
Delhi Capitals                 10
Name: toss_winner, dtype: int64

In [11]:
match_df.winner.value_counts()

Mumbai Indians                 100
Chennai Super Kings             95
Kolkata Knight Riders           84
Kings XI Punjab                 74
Royal Challengers Bangalore     72
Rajasthan Royals                70
Delhi Daredevils                58
Sunrisers Hyderabad             50
Deccan Chargers                 25
Delhi Capitals                  10
Name: winner, dtype: int64

In [12]:
match_df=match_df[['id','city','winner','total_runs']]

In [13]:
delivary_df=delivery.merge(match_df,right_on='id',left_on='match_id')

In [14]:
delivary_df=delivary_df[delivary_df['inning']==2]

In [15]:
pd.set_option('display.max_columns',None)

# current score

In [16]:
delivary_df['current_score']=delivary_df.groupby('id').cumsum()['total_runs_x']

In [17]:
delivary_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_x,player_dismissed,dismissal_kind,fielder,id,city,winner,total_runs_y,current_score
125,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,Mandeep Singh,A Nehra,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1
126,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1
127,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1
128,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,3
129,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152054,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,11415,Hyderabad,Mumbai Indians,152,152
152055,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN,11415,Hyderabad,Mumbai Indians,152,154
152056,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,0,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya,11415,Hyderabad,Mumbai Indians,152,155
152057,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN,11415,Hyderabad,Mumbai Indians,152,157
152058,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,0,0,0,0,0,0,0,0,SN Thakur,lbw,NaN,11415,Hyderabad,Mumbai Indians,152,157

# Runs left

In [18]:
delivary_df['runs_left']=delivary_df['total_runs_y']-delivary_df['current_score']

In [19]:
delivary_df.head(30)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_x,player_dismissed,dismissal_kind,fielder,id,city,winner,total_runs_y,current_score,runs_left
125,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,Mandeep Singh,A Nehra,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1,206
126,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1,206
127,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1,206
128,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,3,204
129,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,7,200
130,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,6,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,11,196
131,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,CH Gayle,Mandeep Singh,B Kumar,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,11,196
132,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,CH Gayle,Mandeep Singh,B Kumar,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,11,196
133,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,CH Gayle,Mandeep Singh,B Kumar,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,12,195
134,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,4,Mandeep Singh,CH Gayle,B Kumar,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,12,195
135,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,Mandeep Singh,CH Gayle,B Kumar,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,12,195
136,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,6,Mandeep Singh,CH Gayle,B Kumar,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,12,195
137,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,CH Gayle,Mandeep Singh,A Nehra,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,12,195
138,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,2,CH Gayle,Mandeep Singh,A Nehra,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,16,191
139,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,3,CH Gayle,Mandeep Singh,A Nehra,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,17,190
140,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,4,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,21,186
141,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,5,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,22,185
142,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,6,CH Gayle,Mandeep Singh,A Nehra,0,0,0,0,0,0,6,0,6,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,28,179
143,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,1,Mandeep Singh,CH Gayle,B Kumar,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,29,178
144,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,2,CH Gayle,Mandeep Singh,B Kumar,0,0,0,0,0,0,6,0,6,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,35,172
145,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,3,CH Gayle,Mandeep Singh,B Kumar,0,0,0,0,0,0,2,0,2,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,37,170
146,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,4,CH Gayle,Mandeep Singh,B Kumar,0,1,0,0,0,0,0,1,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,38,169
147,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,5,CH Gayle,Mandeep Singh,B Kumar,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,38,169
148,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,6,CH Gayle,Mandeep Singh,B Kumar,0,0,0,0,0,0,1,0,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,39,168
149,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,7,Mandeep Singh,CH Gayle,B Kumar,0,0,0,0,0,0,4,0,4,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,43,164
150,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,1,CH Gayle,Mandeep Singh,BCJ Cutting,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,43,164
151,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,2,CH Gayle,Mandeep Singh,BCJ Cutting,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,43,164
152,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,3,CH Gayle,Mandeep Singh,BCJ Cutting,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,43,164
153,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,4,CH Gayle,Mandeep Singh,BCJ Cutting,0,1,0,0,0,0,0,1,1,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,44,163
154,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,5,CH Gayle,Mandeep Singh,BCJ Cutting,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,44,163

# Wicket_left

In [20]:
delivary_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs_x', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'city', 'winner', 'total_runs_y',
       'current_score', 'runs_left'],
      dtype='object')

In [21]:
delivary_df['player_dismissed']=delivary_df['player_dismissed'].fillna("0")
delivary_df['player_dismissed'] = delivary_df['player_dismissed'].apply(lambda x:x if x == "0" else "1")
delivary_df['player_dismissed']=delivary_df['player_dismissed'].astype('int')
wicket=delivary_df.groupby('id').cumsum()['player_dismissed'].values
delivary_df['wicket']=10-wicket

# BALL LEFT

In [22]:
delivary_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs_x', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'city', 'winner', 'total_runs_y',
       'current_score', 'runs_left', 'wicket'],
      dtype='object')

In [23]:
delivary_df['ball_left']=126-(delivary_df['over']*6 + delivary_df['ball'])

In [24]:
##curent run rate
delivary_df['crr']=(delivary_df['current_score']*6)/(120-delivary_df['ball_left'])

In [25]:
delivary_df['rrr']=(delivary_df['runs_left']*6)/delivary_df['ball_left']

In [26]:
delivary_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,wide_runs,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_x,player_dismissed,dismissal_kind,fielder,id,city,winner,total_runs_y,current_score,runs_left,wicket,ball_left,crr,rrr
125,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,Mandeep Singh,A Nehra,0,0,0,0,0,0,1,0,1,0,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1,206,10,119,6.0,10.386555
126,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1,206,10,118,3.0,10.474576
127,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,0,0,0,0,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,1,206,10,117,2.0,10.564103
128,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,2,0,2,0,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,3,204,10,116,4.5,10.551724
129,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,CH Gayle,A Nehra,0,0,0,0,0,0,4,0,4,0,NaN,NaN,1,Hyderabad,Sunrisers Hyderabad,207,7,200,10,115,8.4,10.434783

In [27]:
def result(row):
    return 1 if row.batting_team == row.winner else 0

In [28]:
delivary_df['result']=delivary_df.apply(result,axis=1)

In [29]:
delivary_df.dropna(inplace=True)

In [30]:
delivary_df=delivary_df[delivary_df['ball_left']!=0]

In [31]:
final_df=delivary_df[['batting_team','bowling_team','ball_left','city','runs_left','wicket','total_runs_y','crr','rrr','result']]

In [32]:
final_df.isnull().sum()

batting_team    0
bowling_team    0
ball_left       0
city            0
runs_left       0
wicket          0
total_runs_y    0
crr             0
rrr             0
result          0
dtype: int64

In [33]:
final_df.describe()

,ball_left,runs_left,wicket,total_runs_y,crr,rrr,result
count,2548.000000,2548.000000,2548.000000,2548.000000,2548.000000,2548.000000,2548.000000
mean,53.158556,84.874019,6.045526,170.146389,7.374721,13.495173,0.372841
std,34.876111,51.433417,2.376656,28.987159,2.155312,24.002487,0.483655
min,-2.000000,-12.000000,0.000000,67.000000,0.000000,-222.000000,0.000000
25%,22.000000,42.000000,4.000000,151.000000,6.333333,7.800151,0.000000
50%,50.000000,81.000000,6.000000,171.000000,7.428571,9.867913,0.000000
75%,84.000000,122.000000,8.000000,189.000000,8.634701,13.110197,1.000000
max,119.000000,231.000000,9.000000,250.000000,18.000000,678.000000,1.000000

In [34]:
##Shuffling the data avoid bias output

final_df=final_df.sample(final_df.shape[0])

In [35]:
final_df.head()

,batting_team,bowling_team,ball_left,city,runs_left,wicket,total_runs_y,crr,rrr,result
95040,Rajasthan Royals,Sunrisers Hyderabad,26,Ahmedabad,52,4,134,5.234043,12.000000,0
143490,Mumbai Indians,Kings XI Punjab,67,Mumbai,142,7,204,7.018868,12.716418,1
135966,Royal Challengers Bangalore,Rajasthan Royals,44,Jaipur,75,4,174,7.815789,10.227273,0
82689,Chennai Super Kings,Mumbai Indians,65,Mumbai,99,4,139,4.363636,9.138462,0
40514,Kolkata Knight Riders,Delhi Daredevils,98,Delhi,157,8,177,5.454545,9.612245,0

# MODEL BUILDING

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import  OneHotEncoder

In [37]:
x = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]

In [38]:
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2,random_state=0)

In [39]:
ct=ColumnTransformer([ 
    ('ct',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])],remainder='passthrough')

In [40]:
pip=Pipeline(steps=[
    ('step1',ct),('step2',LogisticRegression(solver="liblinear"))
])

In [41]:
pip.fit(x_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ct',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [42]:
from sklearn.metrics import accuracy_score

In [43]:
y_pred=pip.predict(x_test)

In [44]:
accuracy_score(y_test,y_pred)

0.8

In [45]:
teams

['Sunrisers Hyderabad',
 'Mumbai Indians',
 'Royal Challengers Bangalore',
 'Kolkata Knight Riders',
 'Kings XI Punjab',
 'Chennai Super Kings',
 'Rajasthan Royals',
 'Delhi Capitals']

In [46]:
delivary_df['city'].unique()

array(['Hyderabad', 'Bangalore', 'Mumbai', 'Kolkata', 'Delhi', 'Indore',
       'Chandigarh', 'Jaipur', 'Chennai', 'Cape Town', 'Port Elizabeth',
       'Durban', 'Centurion', 'East London', 'Johannesburg', 'Kimberley',
       'Bloemfontein', 'Ahmedabad', 'Cuttack', 'Nagpur', 'Dharamsala',
       'Visakhapatnam', 'Pune', 'Raipur', 'Ranchi', 'Abu Dhabi',
       'Sharjah', 'Mohali', 'Bengaluru'], dtype=object)

In [47]:
import pickle
pickle.dump(pip,open('pipe.pkl','wb'))

In [48]:
x_train.columns

Index(['batting_team', 'bowling_team', 'ball_left', 'city', 'runs_left',
       'wicket', 'total_runs_y', 'crr', 'rrr'],
      dtype='object')